---
title: "Milestone #5"
author: "Jessica Scazzero"
date: "10/17/19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(readr)
library(tidyverse)
diary <- read_csv(file= "Raw-Data/dcpc_2017_indlevel-csv.csv")
```

```{data cleaning}
#Since my data was a survey carried out by the Federal Reserve tha data set is very well organized. I spent most of my time reading through the codebook on the Fed's website which gave a detailed description of each of the many variables - so I could then select the ones I was most interested in exploring. I also did some work analyzing whether it is better to use the individual level data or transaction level data for the purposes of my final project and the questions I want to answer.
cash <- diary %>%
  select(paypref_lt10, paypref_100plus, paypref_10to25, paypref_25to50, paypref_50to100, age, race_white, race_black, race_asian, income_hh) %>%
  filter(paypref_100plus == 1, paypref_lt10 == 1)
```

##About Section

##Background/Research Questions

Technology has rapidly transformed almost every aspect of our lives - including the way we carry out payments. Within recent years, the devlopment of PayPal, Ripple, Venmo among other mobile money payment systesm have acclerated the presence and access of cashless technologies across societies. But, despite this growth in technology, cash continues to persist both for use in transactions and a store of value. In order to answer this question we must understand: Who is using cash? Who is holding cash? What types of transactions is it used for? And, how often is it used?

##The Data 
To answer this question I used data from the Federal Reserve's Diary of Consumer Payment Choice (DCPC). The DCPC is a survey of consumer payment behavior run in conjunction with the University of Southern California’s Understanding America Study (UAS). Respondents were randomly assigned a three-day period and
asked to track all of their payments using an online questionnaire. I plan to combine data from the 2017, 2016 and 2015 data sets as well as use both the individual level and transaction level data.

##About Me!

My name is Jessica, I'm a senior economics concentrator and I am writing my thesis on a similar topic analyzing the changes in cash demand across countries and across time. I'm really excited to be using data science to observe trends that I can potentially include in my larger inquiry into cash in  my thesis.